
spring:
  datasource:
    url: jdbc:mysql://.../camunda
    driverClassName: org.mariadb.jdbc.Driver
    username: admin
    password: ***


server:
  port: 443
  ssl:
    enabled: true
    key-store: classpath:keystore.jks
    key-store-password: camunda
    key-password: camunda
    key-store-type: JKS


camunda.bpm.admin-user:
  id: admin
  password: admin

