#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
#  datasource:
#    url: jdbc:h2:mem:camunda
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver

#spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

spring:
  datasource:
    url: jdbc:mysql://camundadb.csgxvjgipglh.ap-southeast-1.rds.amazonaws.com:3306/camunda
    driverClassName: org.mariadb.jdbc.Driver
    username: admin
    password: dbsadmin


server:
  port: 443
  ssl:
    enabled: true
    key-store: classpath:keystore.jks
    key-store-password: camunda
    key-password: camunda
    key-store-type: JKS


camunda.bpm.admin-user:
  id: admin
  password: admin

