spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:camunda
    username: sa
    password: password
    driverClassName: org.h2.Driver

spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8080


camunda.bpm.admin-user:
  id: admin
  password: admin